[phases.setup]
nixPkgs = ["php84", "php84Extensions.gd", "php84Extensions.intl", "php84Extensions.zip", "php84Extensions.pdo_mysql"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"