[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"